global:
  web-url: http://localhost:8080
  jwt-secret: dev-secret-key-change-in-production

apps:
  medias:
    - photos:/tmp/nas-test/photos
    
  videos:
    - movies:/tmp/nas-test/videos
    
  music:
    - library:/tmp/nas-test/music
    
  documents:
    - docs:/tmp/nas-test/documents

database:
  host: localhost
  port: 5432
  name: home_nas
  user: postgres
  password: postgres