CREATE TABLE IF NOT EXISTS shares (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    app_type VARCHAR(32) NOT NULL,
    token VARCHAR(32) UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    burn_after_read BOOLEAN NOT NULL DEFAULT FALSE,
    max_views INTEGER NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL
);
